import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { PropsCharacter, QueryParams } from "@/types/types";


const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps({ query }: QueryParams  ) {
  const { id } = query;
  const res = await fetch(`${defaultEndpoint}/${id}`);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Character({ data }: PropsCharacter) {
  const { name, image, gender, location, origin, species, status } = data;

  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{name}</h1>
        <img src={image} alt="character"/>
        <div>
          <h2>Details</h2>
          <ul>
            <li>
              <strong>Name:</strong>
              {name}
            </li>
            <li>
              <strong>gender:</strong>
              {gender}
            </li>
            <li>
              <strong>location:</strong>
              {location?.name}
            </li>
            <li>
              <strong>origin:</strong>
              {origin?.name}
            </li>
            <li>
              <strong>species:</strong>
              {species}
            </li>
            <li>
              <strong>status:</strong>
              {status}
            </li>
          </ul>
        </div>
        <p className="back">
          <Link href="/">
            <p>Back to all characters</p>
          </Link>
        </p>
      </main>
    </>
  );
}
